### ISSUE TITLE
problem with a connection string format

### ISSUE THREAD

**Issue by dkalog** [timescale/timescaledb-parallel-copy#30]
I am trying to use this utility  with url escape beacuse my password has the @ character inside..

 timescaledb-parallel-copy --db-name openmeteo --table enhydris_timeseries_data --connection postgres://postgres:6-@m4
dkalo@eridanos:~/timeseries_data$ timescaledb-parallel-copy --db-name openmeteo --table enhydris_timeseries_data  --connection postgres%3A6-%40m4%26kvZUuBMR%0A_
--file alldata.csv --workers 2 --reporting-period 30s
panic: missing "=" after "postgres%3A6-%40m4%26kvZUuBMR%0A_" in connection info string"

but I receive panic..

goroutine 19 [running]:
github.com/jmoiron/sqlx.MustConnect(...)
        /home/builder/go/src/github.com/jmoiron/sqlx/sqlx.go:650
main.processBatches(0xc00008a2c0, 0xc00008e240)
        /home/builder/go/src/github.com/timescale/timescaledb-parallel-copy/cmd/timescaledb-parallel-copy/main.go:206 +0xd2f
created by main.main
        /home/builder/go/src/github.com/timescale/timescaledb-parallel-copy/cmd/timescaledb-parallel-copy/main.go:124 +0x181
dkalo@eridanos:~/timeseries_data$ timescaledb-parallel-copy --db-name openmeteo --table enhydris_timeseries_data  --connection postgres%3A6-%40m4%26kvZUuBMR%0A_ --file alldata.csv --workers 2 --reporting-period 30s
panic: missing "=" after "postgres%3A6-%40m4%26kvZUuBMR%0A_" in connection info string"

**Comment by MetalBlueberry** [comment]
For future reference, why you don't use the keyword/value format?

https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-KEYWORD-VALUE
