### ISSUE TITLE
nanosecond timestamp support

### ISSUE THREAD

**Issue by timelf123** [timescale/timescaledb-parallel-copy#48]
```
panic: pq: date/time field value out of range: "1612211479269686570"

goroutine 6 [running]:
main.processBatches(0xc00000aec0, 0xc00001c660)
        C:/Users/User/go/src/github.com/timescale/timescaledb-parallel-copy/cmd/timescaledb-parallel-copy/main.go:262 +0x899
created by main.main
        C:/Users/User/go/src/github.com/timescale/timescaledb-parallel-copy/cmd/timescaledb-parallel-copy/main.go:148 +0x1db
```

**Comment by timelf123** [comment]
SELECT create_hypertable('timeseries', 'timestamp', chunk_time_interval => 86400000000000);
