### ISSUE TITLE
(FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))

### ISSUE THREAD

**Issue by Banzaika** [timescale/timescaledb-parallel-copy#70]
I run ```timescaledb-parallel-copy --db-name timescale_parallel_copy --table yuh_general_datapoint --file exported_data.csv --workers 2 --reporting-period 30s  --copy-options "NULL 'NULL' CSV";``` but I get:
panic: could not connect: failed to connect to `host=localhost user=postgres database=timescale_parallel_copy`: failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))

goroutine 6 [running]:
main.processBatches(0x0?, 0x0?)
        /home/builder/go/pkg/mod/github.com/timescale/timescaledb-parallel-copy@v0.4.0/cmd/timescaledb-parallel-copy/main.go:200 +0x674
created by main.main
        /home/builder/go/pkg/mod/github.com/timescale/timescaledb-parallel-copy@v0.4.0/cmd/timescaledb-parallel-copy/main.go:145 +0x4ad

i tried to specify a username to connect but didn't find a flag for that(

**Comment by Banzaika** [comment]
i found the flag '-connection'
