### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by leonardochen** [timescale/timescaledb-parallel-copy#86]
Hello

I tried to run `timescaledb-parallel-copy` release v0.7.1, but I get an error
```
$ ~/go/bin/timescaledb-parallel-copy -db-name tsdb -table table1 -file file.csv -connection "host=xx.tsdb.cloud.timescale.com user=x password=x port=x sslmode=require" -split "|"

fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000058600?)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*WaitGroup).Wait(0x81d890?)
	/usr/local/go/src/sync/waitgroup.go:118 +0x48
github.com/timescale/timescaledb-parallel-copy/pkg/csvcopy.(*Copier).Copy(0xc0000ae000, {0x81d890, 0xa51240}, {0x819f60, 0xc000032188})
	/home/ec2-user/go/pkg/mod/github.com/timescale/timescaledb-parallel-copy@v0.7.1/pkg/csvcopy/csvcopy.go:208 +0x4a9
main.main()
	/home/ec2-user/go/pkg/mod/github.com/timescale/timescaledb-parallel-copy@v0.7.1/cmd/timescaledb-parallel-copy/main.go:136 +0x525

goroutine 8 [chan send]:
github.com/timescale/timescaledb-parallel-copy/internal/batch.Scan({0x81d900, 0xc00006a230}, {0x819f60, 0xc000032188?}, 0xc00008ac40, {0x1388, 0x0, 0x0, 0x0, 0x0})
	/home/ec2-user/go/pkg/mod/github.com/timescale/timescaledb-parallel-copy@v0.7.1/internal/batch/scan.go:117 +0x5da
github.com/timescale/timescaledb-parallel-copy/pkg/csvcopy.(*Copier).Copy.func2()
	/home/ec2-user/go/pkg/mod/github.com/timescale/timescaledb-parallel-copy@v0.7.1/pkg/csvcopy/csvcopy.go:202 +0x94
created by github.com/timescale/timescaledb-parallel-copy/pkg/csvcopy.(*Copier).Copy in goroutine 1
	/home/ec2-user/go/pkg/mod/github.com/timescale/timescaledb-parallel-copy@v0.7.1/pkg/csvcopy/csvcopy.go:200 +0x49c
```

I had the same issue with `v0.7.0`, but it works fine with `v0.6.0`

**Comment by j-kerppola** [comment]
Yes, running to the same issue  with `timescaledb-parallel-copy 0.7.1 (linux amd64)`

```
goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0000aa5a0?)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*WaitGroup).Wait(0x81d950?)
	/usr/local/go/src/sync/waitgroup.go:118 +0x48
github.com/timescale/timescaledb-parallel-copy/pkg/csvcopy.(*Copier).Copy(0xc0000e6000, {0x81d950, 0xa51240}, {0x81a020, 0xc000094178})
	/home/ec2-user/go/pkg/mod/github.com/timescale/timescaledb-parallel-copy@v0.7.1/pkg/csvcopy/csvcopy.go:208 +0x4a9
main.main()
	/home/ec2-user/go/pkg/mod/github.com/timescale/timescaledb-parallel-copy@v0.7.1/cmd/timescaledb-parallel-copy/main.go:136 +0x525

goroutine 20 [chan send]:
github.com/timescale/timescaledb-parallel-copy/internal/batch.Scan({0x81d9c0, 0xc000080230}, {0x81a020, 0xc000094178?}, 0xc0000b8c40, {0x1388, 0x0, 0x0, 0x0, 0x0})
	/home/ec2-user/go/pkg/mod/github.com/timescale/timescaledb-parallel-copy@v0.7.1/internal/batch/scan.go:117 +0x5da
github.com/timescale/timescaledb-parallel-copy/pkg/csvcopy.(*Copier).Copy.func2()
	/home/ec2-user/go/pkg/mod/github.com/timescale/timescaledb-parallel-copy@v0.7.1/pkg/csvcopy/csvcopy.go:202 +0x94
created by github.com/timescale/timescaledb-parallel-copy/pkg/csvcopy.(*Copier).Copy in goroutine 1
	/home/ec2-user/go/pkg/mod/github.com/timescale/timescaledb-parallel-copy@v0.7.1/pkg/csvcopy/csvcopy.go:200 +0x49c

```

**Comment by MetalBlueberry** [comment]
I've been able to reproduce the situation where the csv input data fails to be inserted in the database. See the linked PR

In the meantime, I advise you to check the data you are trying to load in the database, as it is provably failing on the copy operation.
